basePath: /
consumes:
- application/json
host: localhost:1323
info:
  description: Documentation of our awesome API.
  title: awesome.
  version: 1.0.0
paths:
  /hi:
    get:
      operationId: hiSayParams
      parameters:
      - in: body
        name: Body
        schema:
          type: object
      responses:
        "200":
          $ref: '#/responses/hiSaySuccessResponse'
  /hi/{id}/{code}:
    post:
      operationId: hiCreateParams
      parameters:
      - in: path
        name: id
        required: true
        type: string
        x-go-name: Id
      - in: path
        name: code
        required: true
        type: string
        x-go-name: Code
      - in: body
        name: Body
        schema:
          type: object
      responses:
        "200":
          $ref: '#/responses/hiCreateSuccessResponse'
produces:
- application/json
responses:
  hiCreateSuccessResponse:
    description: success response
    schema:
      properties:
        code:
          description: response code
          type: string
          x-go-name: Code
      type: object
  hiSaySuccessResponse:
    description: success response
    schema:
      properties:
        code:
          description: response code
          type: string
          x-go-name: Code
      type: object
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
